services:
  netdata:
    image: 'netdata/netdata:v1.47.4'
    container_name: netdata-xkg8wcwo0wsscsowo4cgo8ow-153910082811
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    volumes:
      - '/data/coolify/applications/xkg8wcwo0wsscsowo4cgo8ow/netdata/config:/etc/netdata'
      - 'xkg8wcwo0wsscsowo4cgo8ow_netdata-lib:/var/lib/netdata'
      - 'xkg8wcwo0wsscsowo4cgo8ow_netdata-cache:/var/cache/netdata'
      - '/proc:/host/proc'
      - '/sys:/host/sys'
      - '/etc/os-release:/host/etc/os-release'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: xkg8wcwo0wsscsowo4cgo8ow
      COOLIFY_CONTAINER_NAME: netdata-xkg8wcwo0wsscsowo4cgo8ow-153910082811
      COOLIFY_URL: 'https://netdata.strudel.marketing'
      COOLIFY_FQDN: netdata.strudel.marketing
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:19999'
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.397
      - coolify.applicationId=10
      - coolify.type=application
      - coolify.name=netdata-xkg8wcwo0wsscsowo4cgo8ow-153910082811
      - coolify.resourceName=strudel-marketingnetdatamain-ro0k4sg4cow840gco0wo044s
      - coolify.projectName=netdata
      - coolify.serviceName=strudel-marketingnetdatamain-ro0k4sg4cow840gco0wo044s
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.routers.netdata.rule=Host(`netdata.strudel.marketing`)
      - traefik.http.routers.netdata.entrypoints=websecure
      - traefik.http.routers.netdata.tls=true
      - traefik.http.routers.netdata.tls.certresolver=letsencrypt
      - traefik.http.services.netdata.loadbalancer.server.port=19999
    networks:
      xkg8wcwo0wsscsowo4cgo8ow: null

volumes:
  xkg8wcwo0wsscsowo4cgo8ow_netdata-lib:
    name: xkg8wcwo0wsscsowo4cgo8ow_netdata-lib
  xkg8wcwo0wsscsowo4cgo8ow_netdata-cache:
    name: xkg8wcwo0wsscsowo4cgo8ow_netdata-cache

networks:
  xkg8wcwo0wsscsowo4cgo8ow:
    name: xkg8wcwo0wsscsowo4cgo8ow
    external: true

configs: {}
secrets: {}
